name: Jail
main: com.graywolf336.jail.JailMain
version: maven-version-number
description: Ban too harsh? Kick/mute/whatever not enough? Jail bad players!
authors: [graywolf336]
website: dev.bukkit.org/server-mods/jail/
softdepend: [WorldEdit, Vault, Multiverse-Core]
load: POSTWORLD
api-version: 1.15

commands:
    jail:
        description: Jail specified player for specified amount of time.
    togglejaildebug:
        description: Toggles whether the plugin is in debugging state or not.
    unjail:
        description: Release a player from jail.
    unjailforce:
        description: Remove player from the database.
    handcuff:
        description: Allows the player to handcuff another player
    unhandcuff:
        description: Allows the player to unhandcuff someone

permissions:
    jail.*:
        children:
            jail.command.*: true
            jail.usercmd.*: true
            jail.modifyjail: true
            jail.usejailstick280: true
            jail.canbestickjailed: true
            jail.openchest: true
            jail.cantbejailed: true
            jail.vote.start: true
            jail.see.broadcast: true
    jail.command.*:
        description: access to all admin commands
        children:
            jail.command.handcuff: true
            jail.command.jail: true
            jail.command.jailcheck: true
            jail.command.jailclear: true
            jail.command.jailclearforce: true
            jail.command.jailcreate: true
            jail.command.jailcreatecells: true
            jail.command.jaildelete: true
            jail.command.jaildeletecell: true
            jail.command.jaildeletecells: true
            jail.command.jailhelp: true
            jail.command.jaillist: true
            jail.command.jaillistcells: true
            jail.command.jailmute: true
            jail.command.jailrecord: true
            jail.command.jailreload: true
            jail.command.jailsigns: true
            jail.command.jailstop: true
            jail.command.jailtelein: true
            jail.command.jailteleout: true
            jail.command.jailtime: true
            jail.command.jailtransfer: true
            jail.command.jailtransferall: true
            jail.command.jailversion: true
            jail.command.toggledebug: true
            jail.command.unjail: true
            jail.command.unjailforce: true
            jail.vote.start: true
    jail.usercmd.*:
        description: access to all user commands
        children:
            jail.usercmd.jailpay: true
            jail.usercmd.jailstatus: true
            jail.usercmd.jailstick: true
            jail.usercmd.jailvote: true
    jail.command.jail:
        default: op
    jail.command.jailcreate:
        default: op
    jail.command.jailcreatecells:
        default: op
    jail.command.jaildelete:
        default: op
    jail.command.jaildeletecell:
        default: op
    jail.command.jaildeletecells:
        default: op
    jail.command.jailhelp:
        default: op
    jail.command.unjail:
        default: op
    jail.command.jailtransfer:
        default: op
    jail.command.jailtransferall:
        default: op
    jail.command.jailcheck:
        default: op
    jail.command.jailtelein:
        default: op
    jail.command.jailteleout:
        default: op
    jail.command.jaillist:
        default: op
    jail.command.jaillistcells:
        default: op
    jail.command.unjailforce:
        default: op
    jail.command.jailclear:
        default: op
    jail.command.jailclearforce:
        default: op
    jail.command.jailmute:
        default: op
    jail.command.jailsigns:
        default: op
    jail.command.jailstop:
        default: op
    jail.command.jailset:
        default: op
    jail.command.jailcreatewe:
        default: op
    jail.command.jailreload:
        default: op
    jail.command.jailrecord:
        default: op
    jail.command.handcuff:
        default: op
    jail.usercmd.jailvote:
        default: true
    jail.usercmd.jailvote.player:
        default: op
    jail.usercmd.jailvote.immune:
        default: op
    jail.usercmd.jailstatus:
        default: true
    jail.usercmd.jailpay:
        default: true
    jail.usercmd.jailstick:
        default: true
    jail.modifyjail:
        default: op
    jail.usejailstick.stick:
        default: op
        description: change stick for another jailstick item
    jail.canbestickjailed:
        default: true
    jail.openchest:
        default: op
    jail.cantbejailed:
        default: op
    jail.command.toggledebug:
        default: op
    jail.command.jailtime:
        default: op
    jail.command.jailversion:
        default: op
    jail.usercmd.jailvote:
        default: op
    jail.vote.start:
        default: op
    jail.see.broadcast:
        default: true